<template>
  <v-container>
    <v-layout row>
      <v-flex xs12 sm6 offset-sm3>
        <h1>{{ $route.name }} page</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus porttitor iaculis. Suspendisse potenti. Curabitur non ex a lorem aliquet pellentesque consectetur in mauris. Nam lacinia, felis in tincidunt laoreet, purus magna rutrum elit, quis gravida sapien mi in nisl. Nunc neque ex, convallis et imperdiet ac, feugiat vel libero. Ut suscipit magna nulla, eget vestibulum lectus interdum vitae. Duis aliquam lectus ut sodales tempus. Suspendisse ex mi, venenatis in libero a, egestas rutrum tortor.
          Duis egestas ex vitae urna imperdiet, molestie accumsan lectus hendrerit. In tristique lacus mauris. Morbi a cursus lorem, id bibendum mauris. In mattis nulla in nisl euismod ullamcorper. Ut aliquet pretium malesuada. Praesent sollicitudin magna vehicula, lobortis massa non, molestie nunc. Duis efficitur dolor a hendrerit vestibulum. Aliquam gravida turpis feugiat ullamcorper sollicitudin. Vestibulum laoreet nibh ac neque varius volutpat. Nulla vel nunc eget magna auctor laoreet sit amet et dolor. Integer enim sem, porttitor sed pulvinar vel, euismod vel dui. Vivamus accumsan egestas odio eget imperdiet. Pellentesque imperdiet iaculis magna sed commodo. Nullam eu nunc imperdiet, volutpat ligula gravida, luctus velit. Nunc vitae scelerisque velit, eu tincidunt augue.
          Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc mattis convallis neque, fermentum pellentesque velit tempus id. Vivamus interdum justo a justo sodales, sed aliquet augue hendrerit. Duis tempus augue id ligula dictum tincidunt. In accumsan metus diam, non pretium tortor elementum vitae. Vestibulum leo neque, commodo pellentesque commodo nec, venenatis et massa. Integer non orci ante. Vestibulum bibendum purus vestibulum urna scelerisque malesuada et quis enim.
          Nullam at elit in metus laoreet lobortis non a ipsum. Vivamus eu iaculis urna. Pellentesque ac velit ornare, condimentum tellus quis, consequat dolor. Integer eu tellus felis. Cras erat metus, hendrerit ut magna dignissim, gravida tincidunt lorem. Fusce sit amet arcu sit amet ipsum vehicula posuere elementum sed nisi. Fusce gravida magna eu sapien iaculis lobortis. Pellentesque congue, felis et elementum pulvinar, sem neque egestas nunc, sed tempor eros neque ac risus. Duis eu nulla euismod, bibendum erat in, dignissim mi. Nam non libero metus.
          Suspendisse pellentesque tincidunt velit. Nunc ac laoreet ipsum. Nulla ultrices non nibh id fermentum. Nam enim nisl, bibendum dapibus porttitor ut, tincidunt et ipsum. In magna eros, volutpat vel lacus at, mattis lobortis arcu. Pellentesque fermentum consectetur ultricies. Ut sed mauris in augue gravida volutpat eu a risus. Sed aliquet tortor mollis tristique blandit. Aenean non enim sed risus gravida commodo.
          Vestibulum vel diam congue, congue augue id, interdum ex. Praesent a tellus sit amet nulla laoreet vestibulum. Quisque sed gravida neque, ac consequat eros. Nulla quis diam faucibus, aliquam felis tincidunt, laoreet purus. Phasellus facilisis arcu vitae tortor fermentum, et rutrum sem laoreet. Maecenas in nibh nunc. Mauris vel faucibus tortor. Nunc at cursus augue. Maecenas dignissim purus id lectus pulvinar interdum. Sed at maximus augue, et varius ipsum. Cras elit mauris, tristique at mauris faucibus, ultricies dignissim urna. Praesent semper ipsum in vulputate tristique. Nunc justo justo, semper nec lorem nec, consectetur condimentum lacus. Integer fringilla, mi vitae lobortis lacinia, dui ipsum dignissim augue, quis viverra ante sem quis lacus.
          Morbi vestibulum vestibulum egestas. Cras ac arcu a mauris elementum molestie at sit amet ex. Nam condimentum consectetur nisi. Suspendisse et neque vehicula, maximus metus gravida, feugiat augue. Nam ac finibus leo, et vestibulum tellus. Praesent mauris velit, molestie non turpis efficitur, cursus malesuada est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras nec tristique enim. Ut urna massa, molestie blandit pretium a, volutpat mollis libero. Phasellus porta nibh turpis, vestibulum elementum orci rutrum eget. Donec augue est, condimentum sit amet tempus id, commodo ac felis. Suspendisse elementum, odio et feugiat dictum, magna ligula consectetur ligula, vitae feugiat ex lacus vel velit.
          Donec turpis ex, porta id rhoncus in, dapibus at tellus. Aenean venenatis pellentesque ligula, ut imperdiet tortor ultrices eget. Donec id libero rhoncus, malesuada est nec, imperdiet libero. Suspendisse fringilla, justo sit amet laoreet consectetur, massa erat iaculis sem, non tincidunt elit diam sit amet erat. Proin lectus nisi, finibus aliquam leo sed, blandit dignissim purus. Cras at maximus purus. Nunc in enim tellus. Morbi volutpat convallis sodales. Sed ut ipsum non enim auctor dignissim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
          Vestibulum vel condimentum dui. Integer nisi velit, tempus eleifend euismod eget, tincidunt quis magna. Sed lectus est, bibendum a felis nec, tristique blandit turpis. Donec in finibus metus, at ultrices massa. Nulla vitae augue a est semper dapibus. Duis eget diam tellus. Aliquam a diam metus. Integer luctus orci at rhoncus maximus. Duis consectetur maximus odio in interdum. Etiam cursus, tellus ac volutpat malesuada, risus purus pretium mi, tincidunt gravida diam quam sit amet lorem. Aenean ullamcorper sapien vel risus rutrum, nec consequat nisi iaculis. Suspendisse sodales dui in quam bibendum porta. Quisque gravida elit dignissim metus ultricies tincidunt.
          Fusce volutpat euismod mauris, ac maximus elit rutrum nec. Mauris sed justo id turpis consequat ultrices a id lorem. In hac habitasse platea dictumst. Nullam lacinia lobortis ligula ut aliquam. Phasellus aliquam commodo ipsum. Fusce ullamcorper facilisis nibh in dapibus. Integer fringilla sagittis mi. Integer sed tellus enim. Aenean ornare, ante quis tincidunt volutpat, ligula libero pretium sapien, at imperdiet eros magna vitae ipsum. Nam est nisl, commodo vitae congue a, vulputate id massa. Nullam posuere hendrerit metus, non pulvinar massa scelerisque nec. Praesent condimentum dolor eget consequat consequat. Curabitur nisi ante, auctor vitae facilisis nec, feugiat ut velit. Mauris sodales risus at tortor suscipit molestie. Quisque bibendum vestibulum ultrices. Duis enim justo, ullamcorper sit amet libero id, lobortis porttitor nulla.
          Integer quis bibendum nisi. Proin cursus congue elit finibus condimentum. Praesent magna erat, mollis a dui vel, accumsan pharetra sapien. Etiam sed justo ut lacus ultrices rhoncus eu quis ante. Phasellus interdum auctor ex, at tempus urna ornare nec. Donec tincidunt mi lacus, id faucibus leo egestas vel. Sed bibendum, sapien pulvinar convallis consequat, ex diam tempor mi, vitae porttitor sapien arcu a diam. Nam molestie, lacus in mattis pharetra, risus dolor vehicula erat, vel faucibus lectus tellus pretium massa. Quisque malesuada urna sit amet efficitur dictum.
          Nulla id leo imperdiet, egestas turpis eget, ornare velit. Donec sed congue lectus, id elementum dui. Nullam posuere odio ut diam faucibus luctus. Donec purus mauris, ultricies ut eros sit amet, convallis malesuada ipsum. Aliquam sit amet mi et neque consequat varius. Ut quis justo feugiat odio imperdiet viverra. Duis quis arcu maximus, sagittis turpis iaculis, porttitor libero. Donec vel sodales magna, consectetur pulvinar mauris.
        </p>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>
// @ is an alias to /src
import Text from "@/mixins/Text.js"
export default {
  name: "About",
  mixins: [Text],
}
</script>
